// Generated from tools/blockboy-webui.html - do not edit by hand.
// Regenerate with: python tools/gen_webui_h.py
static const char webui_html[] =
"<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>BlockBoy — SD Card</title>\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<style>\n"
":root {\n"
"  --bg: #eef0e6;\n"
"  --surface: #ffffff;\n"
"  --surface2: #e3e6d8;\n"
"  --ink: #232819;\n"
"  --muted: #6b7260;\n"
"  --line: #c9cdbb;\n"
"  --accent: #55731f;\n"
"  --accent-ink: #ffffff;\n"
"  --screen: #b7c98a;\n"
"  --screen-ink: #2c3a12;\n"
"  --danger: #a63a24;\n"
"  --shadow: #9aa088;\n"
"  --mono: ui-monospace, \"Cascadia Mono\", \"Roboto Mono\", Menlo, Consolas, monospace;\n"
"  --sans: -apple-system, \"Segoe UI\", Roboto, system-ui, \"Helvetica Neue\", sans-serif;\n"
"}\n"
"@media (prefers-color-scheme: dark) {\n"
"  :root {\n"
"    --bg: #171a13; --surface: #21251b; --surface2: #2a2f22; --ink: #e6e9da;\n"
"    --muted: #99a188; --line: #383e2d; --accent: #9bbb3c; --accent-ink: #1a2005;\n"
"    --screen: #33401c; --screen-ink: #c4d896; --danger: #e0684a; --shadow: #0c0e09;\n"
"  }\n"
"}\n"
":root[data-theme=\"light\"] {\n"
"  --bg: #eef0e6; --surface: #ffffff; --surface2: #e3e6d8; --ink: #232819;\n"
"  --muted: #6b7260; --line: #c9cdbb; --accent: #55731f; --accent-ink: #ffffff;\n"
"  --screen: #b7c98a; --screen-ink: #2c3a12; --danger: #a63a24; --shadow: #9aa088;\n"
"}\n"
":root[data-theme=\"dark\"] {\n"
"  --bg: #171a13; --surface: #21251b; --surface2: #2a2f22; --ink: #e6e9da;\n"
"  --muted: #99a188; --line: #383e2d; --accent: #9bbb3c; --accent-ink: #1a2005;\n"
"  --screen: #33401c; --screen-ink: #c4d896; --danger: #e0684a; --shadow: #0c0e09;\n"
"}\n"
"* { box-sizing: border-box; }\n"
"html, body { margin: 0; }\n"
"body {\n"
"  background: var(--bg); color: var(--ink);\n"
"  font-family: var(--sans); font-size: 15px; line-height: 1.45;\n"
"  -webkit-tap-highlight-color: transparent;\n"
"}\n"
".wrap { max-width: 760px; margin: 0 auto; padding: 0 12px 110px; }\n"
"\n"
"/* ---------- header ---------- */\n"
"header { display: flex; align-items: center; gap: 12px; padding: 14px 2px 8px; }\n"
".brand { display: flex; flex-direction: column; min-width: 0; }\n"
".brand b { font-family: var(--mono); font-size: 19px; letter-spacing: -0.5px; line-height: 1.1; }\n"
".brand span { font-size: 11px; text-transform: uppercase; letter-spacing: 1.4px; color: var(--muted); }\n"
".demo-pill {\n"
"  margin-left: auto; flex: none;\n"
"  font-family: var(--mono); font-size: 11px; letter-spacing: 0.5px;\n"
"  padding: 3px 9px; border-radius: 999px;\n"
"  background: var(--screen); color: var(--screen-ink);\n"
"  display: none;\n"
"}\n"
".demo .demo-pill { display: inline-block; }\n"
"\n"
"/* ---------- device status strip ---------- */\n"
".devbar {\n"
"  display: none; align-items: center; gap: 14px;\n"
"  font-family: var(--mono); font-size: 11.5px; color: var(--muted);\n"
"  padding: 0 2px 10px; flex-wrap: wrap;\n"
"  font-variant-numeric: tabular-nums;\n"
"}\n"
".devbar.on { display: flex; }\n"
".devbar .cell { display: flex; align-items: center; gap: 6px; white-space: nowrap; }\n"
".devbar .batt { width: 22px; height: 11px; border: 1.5px solid var(--muted); border-radius: 3px; position: relative; }\n"
".devbar .batt::after { content: \"\"; position: absolute; right: -4px; top: 2.5px; width: 2.5px; height: 4px; background: var(--muted); border-radius: 0 1px 1px 0; }\n"
".devbar .batt i { position: absolute; inset: 1.5px; width: var(--lvl, 50%); background: var(--accent); border-radius: 1px; }\n"
".devbar .batt.low i { background: var(--danger); }\n"
".devbar .spacefill { flex: 1; min-width: 110px; display: flex; align-items: center; gap: 8px; justify-content: flex-end; }\n"
".devbar .track { width: 90px; height: 5px; border-radius: 3px; background: var(--surface2); border: 1px solid var(--line); overflow: hidden; }\n"
".devbar .track i { display: block; height: 100%; width: var(--used, 0%); background: var(--accent); }\n"
"\n"
"/* ---------- breadcrumb \"screen\" ---------- */\n"
".pathbar {\n"
"  background: var(--screen); color: var(--screen-ink);\n"
"  border-radius: 8px; border: 2px solid var(--line);\n"
"  box-shadow: inset 0 2px 6px rgba(0,0,0,0.22);\n"
"  padding: 8px 10px;\n"
"  display: flex; align-items: center; gap: 2px;\n"
"  overflow-x: auto; white-space: nowrap;\n"
"  font-family: var(--mono); font-size: 13px;\n"
"  scrollbar-width: none;\n"
"}\n"
".pathbar::-webkit-scrollbar { display: none; }\n"
".pathbar button {\n"
"  appearance: none; border: 0; background: none; font: inherit; color: inherit;\n"
"  padding: 4px 6px; border-radius: 5px; cursor: pointer;\n"
"}\n"
".pathbar button:hover, .pathbar button:focus-visible { background: rgba(0,0,0,0.14); outline: none; }\n"
".pathbar .sep { opacity: 0.55; }\n"
".pathbar .here { font-weight: 700; padding: 4px 6px; }\n"
"\n"
"/* ---------- toolbar ---------- */\n"
".toolbar { display: flex; gap: 8px; align-items: center; padding: 12px 0 0; flex-wrap: wrap; }\n"
".btn {\n"
"  appearance: none; cursor: pointer;\n"
"  font: 600 14px var(--sans);\n"
"  display: inline-flex; align-items: center; gap: 7px;\n"
"  padding: 9px 13px; min-height: 40px;\n"
"  color: var(--ink); background: var(--surface);\n"
"  border: 2px solid var(--line); border-radius: 8px;\n"
"  box-shadow: 0 2px 0 var(--shadow);\n"
"  transition: transform 60ms ease, box-shadow 60ms ease;\n"
"}\n"
".btn:active { transform: translateY(2px); box-shadow: 0 0 0 var(--shadow); }\n"
".btn:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }\n"
".btn.primary { background: var(--accent); border-color: var(--accent); color: var(--accent-ink); }\n"
".btn.icon { padding: 9px 11px; }\n"
".btn.active { background: var(--screen); border-color: var(--accent); color: var(--screen-ink); }\n"
".btn svg { flex: none; }\n"
".spacer { flex: 1; }\n"
"@media (prefers-reduced-motion: reduce) {\n"
"  .btn, .sheet, .modal-card, .toast { transition: none !important; animation: none !important; }\n"
"}\n"
"\n"
"/* ---------- search ---------- */\n"
".searchrow { position: relative; padding: 10px 0; }\n"
".searchrow svg { position: absolute; left: 12px; top: 50%; transform: translateY(-50%); color: var(--muted); pointer-events: none; }\n"
".searchrow input {\n"
"  width: 100%; padding: 10px 34px 10px 36px; min-height: 40px;\n"
"  font: 14px var(--sans); color: var(--ink);\n"
"  background: var(--surface); border: 2px solid var(--line); border-radius: 8px;\n"
"}\n"
".searchrow input:focus-visible { outline: none; border-color: var(--accent); }\n"
".searchrow .clear {\n"
"  position: absolute; right: 6px; top: 50%; transform: translateY(-50%);\n"
"  appearance: none; border: 0; background: none; color: var(--muted);\n"
"  width: 32px; height: 32px; border-radius: 6px; cursor: pointer; display: none;\n"
"}\n"
".searchrow .clear:hover { background: var(--surface2); }\n"
".searchrow.has-q .clear { display: block; }\n"
"\n"
"/* ---------- upload progress ---------- */\n"
".uploads { display: flex; flex-direction: column; gap: 6px; margin-bottom: 10px; }\n"
".up-item { background: var(--surface); border: 1px solid var(--line); border-radius: 8px; padding: 8px 12px; }\n"
".up-item .nm { display: flex; justify-content: space-between; gap: 10px; font-family: var(--mono); font-size: 12.5px; }\n"
".up-item .nm em { font-style: normal; color: var(--muted); font-variant-numeric: tabular-nums; }\n"
".up-item .track { height: 5px; margin-top: 6px; border-radius: 3px; background: var(--surface2); overflow: hidden; }\n"
".up-item .fill { height: 100%; width: 0%; background: var(--accent); border-radius: 3px; }\n"
"\n"
"/* ---------- file list ---------- */\n"
".list { background: var(--surface); border: 1px solid var(--line); border-radius: 10px; overflow: hidden; }\n"
".row {\n"
"  display: flex; align-items: center; gap: 12px;\n"
"  width: 100%; padding: 0 6px 0 12px; min-height: 54px;\n"
"  border: 0; border-bottom: 1px solid var(--line);\n"
"  background: none; color: inherit; font: inherit;\n"
"  text-align: left; cursor: pointer;\n"
"}\n"
".list > :last-child { border-bottom: 0; }\n"
".row:hover { background: var(--surface2); }\n"
".row:focus-visible { outline: 2px solid var(--accent); outline-offset: -3px; }\n"
".row.checked { background: color-mix(in srgb, var(--accent) 14%, var(--surface)); }\n"
".row .fic { flex: none; width: 26px; display: flex; justify-content: center; }\n"
".row .cbox {\n"
"  width: 20px; height: 20px; border-radius: 6px;\n"
"  border: 2px solid var(--muted); flex: none;\n"
"  display: flex; align-items: center; justify-content: center;\n"
"  color: transparent;\n"
"}\n"
".row.checked .cbox { background: var(--accent); border-color: var(--accent); color: var(--accent-ink); }\n"
".row .info { flex: 1; min-width: 0; padding: 8px 0; }\n"
".row .name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-weight: 500; }\n"
".row .meta {\n"
"  font-family: var(--mono); font-size: 11.5px; color: var(--muted);\n"
"  font-variant-numeric: tabular-nums;\n"
"  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;\n"
"}\n"
".row .kebab {\n"
"  flex: none; appearance: none; border: 0; background: none; cursor: pointer;\n"
"  width: 42px; height: 42px; border-radius: 8px;\n"
"  display: flex; align-items: center; justify-content: center;\n"
"  color: var(--muted);\n"
"}\n"
".row .kebab:hover { background: var(--line); color: var(--ink); }\n"
".row .kebab:focus-visible { outline: 2px solid var(--accent); }\n"
".empty { padding: 42px 20px; text-align: center; color: var(--muted); }\n"
".empty b { display: block; color: var(--ink); margin-bottom: 4px; }\n"
".count { padding: 10px 4px; font-family: var(--mono); font-size: 11.5px; color: var(--muted); text-align: center; }\n"
"\n"
"/* ---------- selection bar ---------- */\n"
".bulkbar {\n"
"  position: fixed; left: 50%; bottom: 14px; transform: translateX(-50%) translateY(90px);\n"
"  z-index: 35; display: flex; gap: 8px; align-items: center;\n"
"  background: var(--surface); border: 2px solid var(--line); border-radius: 12px;\n"
"  box-shadow: 0 6px 24px rgba(0,0,0,0.3);\n"
"  padding: 8px 10px; max-width: calc(100vw - 20px);\n"
"  transition: transform 200ms ease;\n"
"}\n"
".bulkbar.on { transform: translateX(-50%) translateY(0); }\n"
".bulkbar .n { font: 600 13px var(--mono); padding: 0 6px; white-space: nowrap; }\n"
".bulkbar .btn { min-height: 38px; padding: 7px 11px; font-size: 13px; }\n"
"\n"
"/* ---------- action sheet / dropdown ---------- */\n"
".scrim { position: fixed; inset: 0; background: rgba(0,0,0,0.45); display: none; z-index: 40; }\n"
".scrim.open { display: block; }\n"
".sheet {\n"
"  position: fixed; left: 0; right: 0; bottom: -100%;\n"
"  z-index: 41; background: var(--surface);\n"
"  border-radius: 16px 16px 0 0; border-top: 2px solid var(--line);\n"
"  padding: 10px 14px calc(14px + env(safe-area-inset-bottom));\n"
"  max-width: 560px; margin: 0 auto;\n"
"  transition: bottom 200ms ease;\n"
"}\n"
".sheet.open { bottom: 0; }\n"
".sheet .grip { width: 36px; height: 4px; border-radius: 2px; background: var(--line); margin: 2px auto 10px; }\n"
".sheet h4 {\n"
"  margin: 0 0 8px; font-family: var(--mono); font-size: 13px; font-weight: 400; color: var(--muted);\n"
"  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;\n"
"}\n"
".sheet button.item {\n"
"  display: flex; align-items: center; gap: 12px;\n"
"  width: 100%; min-height: 48px; padding: 0 10px;\n"
"  appearance: none; background: none; border: 0; border-radius: 8px;\n"
"  font: 500 15px var(--sans); color: var(--ink); cursor: pointer; text-align: left;\n"
"}\n"
".sheet button.item:hover, .sheet button.item:focus-visible { background: var(--surface2); outline: none; }\n"
".sheet button.item.danger { color: var(--danger); }\n"
".sheet button.item .now { margin-left: auto; color: var(--accent); }\n"
"\n"
"/* ---------- modal ---------- */\n"
".modal {\n"
"  position: fixed; inset: 0; z-index: 50;\n"
"  display: none; align-items: center; justify-content: center;\n"
"  background: rgba(0,0,0,0.45); padding: 16px;\n"
"}\n"
".modal.open { display: flex; }\n"
".modal-card {\n"
"  background: var(--surface); border: 2px solid var(--line); border-radius: 12px;\n"
"  width: 100%; max-width: 400px; padding: 18px;\n"
"  box-shadow: 0 8px 30px rgba(0,0,0,0.35);\n"
"  max-height: 86vh; display: flex; flex-direction: column;\n"
"}\n"
".modal-card h3 { margin: 0 0 4px; font-size: 16px; }\n"
".modal-card p { margin: 0 0 12px; font-size: 13px; color: var(--muted); overflow-wrap: anywhere; }\n"
".modal-card input {\n"
"  width: 100%; padding: 10px 12px; margin-bottom: 14px;\n"
"  font: 14px var(--mono); color: var(--ink);\n"
"  background: var(--bg); border: 2px solid var(--line); border-radius: 8px;\n"
"}\n"
".modal-card input:focus-visible { outline: none; border-color: var(--accent); }\n"
".modal-actions { display: flex; gap: 8px; justify-content: flex-end; }\n"
".btn.danger { background: var(--danger); border-color: var(--danger); color: #fff; }\n"
"\n"
"/* folder picker inside modal */\n"
".picker-path {\n"
"  font-family: var(--mono); font-size: 12px; color: var(--screen-ink);\n"
"  background: var(--screen); border-radius: 6px; padding: 6px 10px; margin-bottom: 8px;\n"
"  overflow-x: auto; white-space: nowrap; scrollbar-width: none;\n"
"}\n"
".picker-list { border: 1px solid var(--line); border-radius: 8px; overflow-y: auto; min-height: 120px; max-height: 40vh; margin-bottom: 14px; }\n"
".picker-list button {\n"
"  display: flex; align-items: center; gap: 10px;\n"
"  width: 100%; min-height: 44px; padding: 0 12px;\n"
"  appearance: none; background: none; border: 0; border-bottom: 1px solid var(--line);\n"
"  font: 500 14px var(--sans); color: var(--ink); cursor: pointer; text-align: left;\n"
"}\n"
".picker-list button:last-child { border-bottom: 0; }\n"
".picker-list button:hover, .picker-list button:focus-visible { background: var(--surface2); outline: none; }\n"
".picker-list .none { padding: 20px; text-align: center; color: var(--muted); font-size: 13px; }\n"
"\n"
"/* ---------- image / text viewer ---------- */\n"
".viewer-card { max-width: min(680px, 94vw); }\n"
".viewer-card img { max-width: 100%; max-height: 60vh; display: block; margin: 0 auto 14px; border-radius: 8px; background: var(--surface2); image-rendering: pixelated; }\n"
".viewer-card pre {\n"
"  background: var(--bg); border: 1px solid var(--line); border-radius: 8px;\n"
"  padding: 12px; margin: 0 0 14px;\n"
"  font: 12px/1.5 var(--mono); overflow: auto; max-height: 55vh; white-space: pre-wrap; overflow-wrap: anywhere;\n"
"}\n"
"\n"
"/* ---------- toast ---------- */\n"
".toast {\n"
"  position: fixed; left: 50%; bottom: 22px; transform: translateX(-50%) translateY(80px);\n"
"  z-index: 60; background: var(--ink); color: var(--bg);\n"
"  font: 500 13.5px var(--sans);\n"
"  padding: 10px 18px; border-radius: 999px;\n"
"  max-width: min(90vw, 480px);\n"
"  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;\n"
"  transition: transform 220ms ease; pointer-events: none;\n"
"}\n"
".toast.show { transform: translateX(-50%) translateY(0); }\n"
"\n"
"/* ---------- desktop ---------- */\n"
"@media (min-width: 640px) {\n"
"  body { font-size: 14px; }\n"
"  .row { min-height: 46px; }\n"
"  .row .info { display: flex; align-items: baseline; gap: 14px; }\n"
"  .row .name { flex: 1; }\n"
"  .row .meta { flex: none; width: 210px; text-align: right; }\n"
"  .sheet {\n"
"    position: absolute; left: auto; right: auto; bottom: auto;\n"
"    /* Desktop has no slide-in, so visibility is a plain display toggle. Without\n"
"       this the closed sheet stayed on screen (mobile hides it via bottom:-100%,\n"
"       which desktop overrides to auto) and no dismiss could hide it. */\n"
"    display: none;\n"
"    border-radius: 10px; border: 2px solid var(--line);\n"
"    padding: 6px; width: 230px; height: auto;\n"
"    box-shadow: 0 6px 24px rgba(0,0,0,0.25);\n"
"    transition: none;\n"
"  }\n"
"  .sheet.open { display: block; bottom: auto; }\n"
"  .sheet .grip, .sheet h4 { display: none; }\n"
"  .sheet button.item { min-height: 40px; font-size: 14px; }\n"
"  .scrim { background: transparent; }\n"
"}\n"
".drophint {\n"
"  position: fixed; inset: 10px; z-index: 30; display: none;\n"
"  border: 3px dashed var(--accent); border-radius: 14px;\n"
"  background: color-mix(in srgb, var(--accent) 12%, transparent);\n"
"  align-items: center; justify-content: center;\n"
"  font: 700 18px var(--sans); color: var(--accent);\n"
"  pointer-events: none;\n"
"}\n"
"body.dragging .drophint { display: flex; }\n"
"</style></head><body>\n"
"\n"
"<div class=\"wrap\">\n"
"  <header>\n"
"    <div class=\"brand\">\n"
"      <b>BlockBoy</b>\n"
"      <span>SD-card manager</span>\n"
"    </div>\n"
"    <span class=\"demo-pill\">demo</span>\n"
"  </header>\n"
"\n"
"  <div class=\"devbar\" id=\"devbar\">\n"
"    <span class=\"cell\"><span class=\"batt\" id=\"batt\"><i></i></span><span id=\"batt-txt\"></span></span>\n"
"    <span class=\"cell\" id=\"fw-txt\"></span>\n"
"    <span class=\"spacefill\"><span id=\"space-txt\"></span><span class=\"track\"><i id=\"space-fill\"></i></span></span>\n"
"  </div>\n"
"\n"
"  <nav class=\"pathbar\" id=\"pathbar\" aria-label=\"Folder path\"></nav>\n"
"\n"
"  <div class=\"toolbar\">\n"
"    <button class=\"btn primary\" id=\"btn-upload\">\n"
"      <svg width=\"15\" height=\"15\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 12V3M4 7l4-4 4 4M2 13.5h12\"/></svg>\n"
"      Upload\n"
"    </button>\n"
"    <input type=\"file\" id=\"upload\" multiple hidden>\n"
"    <button class=\"btn\" id=\"btn-newfolder\">\n"
"      <svg width=\"15\" height=\"15\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1.5 4.5v8h13v-6.5H8L6.5 4.5z\"/><path d=\"M11 8v3M9.5 9.5h3\"/></svg>\n"
"      New folder\n"
"    </button>\n"
"    <span class=\"spacer\"></span>\n"
"    <button class=\"btn icon\" id=\"btn-select\" aria-label=\"Select multiple\">\n"
"      <svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"2\" y=\"2\" width=\"9\" height=\"9\" rx=\"2\"/><path d=\"M4.8 6.6l1.6 1.6 3-3.4\"/><path d=\"M14 6v6a2 2 0 0 1-2 2H6\"/></svg>\n"
"    </button>\n"
"    <button class=\"btn icon\" id=\"btn-sort\" aria-label=\"Sort\">\n"
"      <svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 3v10M5 13l-2.5-2.5M5 13l2.5-2.5M11 13V3M11 3L8.5 5.5M11 3l2.5 2.5\"/></svg>\n"
"    </button>\n"
"    <button class=\"btn icon\" id=\"btn-refresh\" aria-label=\"Refresh\">\n"
"      <svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13.5 8a5.5 5.5 0 1 1-1.6-3.9M13.5 1.5v3h-3\"/></svg>\n"
"    </button>\n"
"  </div>\n"
"\n"
"  <div class=\"searchrow\" id=\"searchrow\">\n"
"    <svg width=\"15\" height=\"15\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\"><circle cx=\"7\" cy=\"7\" r=\"4.5\"/><path d=\"M10.5 10.5L14 14\"/></svg>\n"
"    <input type=\"search\" id=\"search\" placeholder=\"Search in this folder\" autocomplete=\"off\">\n"
"    <button class=\"clear\" id=\"search-clear\" aria-label=\"Clear search\">✕</button>\n"
"  </div>\n"
"\n"
"  <div class=\"uploads\" id=\"uploads\"></div>\n"
"\n"
"  <div class=\"list\" id=\"list\" role=\"list\"></div>\n"
"  <div class=\"count\" id=\"count\"></div>\n"
"</div>\n"
"\n"
"<div class=\"drophint\">Drop files to upload</div>\n"
"\n"
"<div class=\"bulkbar\" id=\"bulkbar\">\n"
"  <span class=\"n\" id=\"bulk-n\">0</span>\n"
"  <button class=\"btn\" id=\"bulk-download\">Download</button>\n"
"  <button class=\"btn\" id=\"bulk-move\">Move</button>\n"
"  <button class=\"btn danger\" id=\"bulk-delete\">Delete</button>\n"
"  <button class=\"btn icon\" id=\"bulk-cancel\" aria-label=\"Cancel selection\">✕</button>\n"
"</div>\n"
"\n"
"<div class=\"scrim\" id=\"scrim\"></div>\n"
"<div class=\"sheet\" id=\"sheet\" role=\"menu\"></div>\n"
"\n"
"<div class=\"modal\" id=\"modal\">\n"
"  <div class=\"modal-card\" role=\"dialog\" aria-modal=\"true\">\n"
"    <h3 id=\"m-title\"></h3>\n"
"    <p id=\"m-text\"></p>\n"
"    <input id=\"m-input\" type=\"text\" autocomplete=\"off\" spellcheck=\"false\">\n"
"    <div class=\"modal-actions\">\n"
"      <button class=\"btn\" id=\"m-cancel\">Cancel</button>\n"
"      <button class=\"btn primary\" id=\"m-ok\">OK</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"modal\" id=\"picker\">\n"
"  <div class=\"modal-card\" role=\"dialog\" aria-modal=\"true\">\n"
"    <h3>Move to…</h3>\n"
"    <div class=\"picker-path\" id=\"p-path\"></div>\n"
"    <div class=\"picker-list\" id=\"p-list\"></div>\n"
"    <div class=\"modal-actions\">\n"
"      <button class=\"btn\" id=\"p-cancel\">Cancel</button>\n"
"      <button class=\"btn primary\" id=\"p-ok\">Move here</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"modal\" id=\"viewer\">\n"
"  <div class=\"modal-card viewer-card\" role=\"dialog\" aria-modal=\"true\">\n"
"    <h3 id=\"v-title\"></h3>\n"
"    <img id=\"v-img\" alt=\"\" hidden>\n"
"    <pre id=\"v-pre\" hidden></pre>\n"
"    <div class=\"modal-actions\">\n"
"      <button class=\"btn\" id=\"v-download\">Download</button>\n"
"      <button class=\"btn primary\" id=\"v-close\">Close</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"toast\" id=\"toast\"></div>\n"
"\n"
"<script>\n"
"\"use strict\";\n"
"const $ = s => document.querySelector(s);\n"
"const ROOT = \"/sd\";\n"
"let path = ROOT;\n"
"let demo = false;\n"
"\n"
"/* ---------- tiny helpers ---------- */\n"
"const fmtSize = n => {\n"
"  if (n >= 1073741824) return (n / 1073741824).toFixed(1) + \" GB\";\n"
"  if (n >= 1048576) return (n / 1048576).toFixed(1) + \" MB\";\n"
"  if (n >= 1024) return (n / 1024).toFixed(1) + \" KB\";\n"
"  return n + \" B\";\n"
"};\n"
"const fmtDate = t => {\n"
"  if (!t) return \"\";\n"
"  const d = new Date(t * 1000);\n"
"  const p = x => String(x).padStart(2, \"0\");\n"
"  return `${p(d.getDate())}-${p(d.getMonth()+1)}-${d.getFullYear()} ${p(d.getHours())}:${p(d.getMinutes())}`;\n"
"};\n"
"const ROM_EXT = [\"gb\",\"gbc\",\"gba\",\"nes\",\"fds\",\"sms\",\"gg\",\"sg\",\"md\",\"gen\",\"col\",\"pce\",\"zip\",\"lua\"];\n"
"const IMG_EXT = [\"png\",\"jpg\",\"jpeg\",\"bmp\",\"gif\"];\n"
"const TXT_EXT = [\"txt\",\"log\",\"json\",\"ini\",\"cfg\",\"md\",\"sav\"];\n"
"const ext = n => (n.match(/\\.([a-z0-9]+)$/i) || [,\"\"])[1].toLowerCase();\n"
"const isRom = f => !f.is_dir && ROM_EXT.includes(ext(f.name));\n"
"const isImg = f => !f.is_dir && IMG_EXT.includes(ext(f.name));\n"
"const isTxt = f => !f.is_dir && [\"txt\",\"log\",\"json\",\"ini\",\"cfg\",\"md\"].includes(ext(f.name));\n"
"const esc = s => s.replace(/[&<>\"']/g, c => ({ \"&\":\"&amp;\",\"<\":\"&lt;\",\">\":\"&gt;\",'\"':\"&quot;\",\"'\":\"&#39;\" }[c]));\n"
"const parentOf = p => p.slice(0, p.lastIndexOf(\"/\")) || ROOT;\n"
"// Encode a filesystem path for use in a URL, keeping the \"/\" separators intact.\n"
"// Without this, names with spaces or & # ( ) etc. break the request → failed\n"
"// downloads and broken image previews.\n"
"const urlPath = p => p.split(\"/\").map(encodeURIComponent).join(\"/\");\n"
"\n"
"function icon(f) {\n"
"  if (f.is_dir) return `<svg width=\"20\" height=\"20\" viewBox=\"0 0 16 16\" fill=\"var(--accent)\"><path d=\"M1.5 4a1 1 0 0 1 1-1h3.6l1.4 1.5h6a1 1 0 0 1 1 1V12a1 1 0 0 1-1 1h-11a1 1 0 0 1-1-1z\"/></svg>`;\n"
"  const e = ext(f.name);\n"
"  if (ROM_EXT.includes(e)) return `<svg width=\"20\" height=\"20\" viewBox=\"0 0 16 16\" fill=\"none\"><rect x=\"3\" y=\"1.5\" width=\"10\" height=\"13\" rx=\"1.5\" fill=\"var(--surface2)\" stroke=\"var(--muted)\" stroke-width=\"1.3\"/><rect x=\"5\" y=\"4\" width=\"6\" height=\"4.5\" rx=\"0.5\" fill=\"var(--screen)\"/><rect x=\"5\" y=\"10.5\" width=\"3\" height=\"1.6\" fill=\"var(--muted)\"/></svg>`;\n"
"  if (IMG_EXT.includes(e)) return `<svg width=\"20\" height=\"20\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"var(--muted)\" stroke-width=\"1.3\"><rect x=\"2\" y=\"3\" width=\"12\" height=\"10\" rx=\"1\"/><circle cx=\"6\" cy=\"7\" r=\"1.2\" fill=\"var(--muted)\" stroke=\"none\"/><path d=\"M3.5 12l3-3 2 2 2.5-2.8 1.5 1.8\"/></svg>`;\n"
"  if (TXT_EXT.includes(e)) return `<svg width=\"20\" height=\"20\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"var(--muted)\" stroke-width=\"1.3\" stroke-linecap=\"round\"><path d=\"M4 1.5h6l2.5 2.5V14.5h-8.5z\" fill=\"var(--surface2)\"/><path d=\"M6 7h4M6 9.5h4M6 12h2.5\"/></svg>`;\n"
"  return `<svg width=\"20\" height=\"20\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"var(--muted)\" stroke-width=\"1.3\"><path d=\"M4 1.5h6l2.5 2.5V14.5h-8.5z\" fill=\"var(--surface2)\"/></svg>`;\n"
"}\n"
"\n"
"let toastTimer;\n"
"function toast(msg) {\n"
"  const t = $(\"#toast\");\n"
"  t.textContent = msg;\n"
"  t.classList.add(\"show\");\n"
"  clearTimeout(toastTimer);\n"
"  toastTimer = setTimeout(() => t.classList.remove(\"show\"), 2600);\n"
"}\n"
"\n"
"/* ---------- demo backend (used when the real API is unreachable) ---------- */\n"
"const now = Date.now() / 1000 | 0, day = 86400;\n"
"const demoFS = {\n"
"  \"/sd\": [\n"
"    { name: \"roms\", is_dir: true, size: 0, mtime: now - 30*day },\n"
"    { name: \"romart\", is_dir: true, size: 0, mtime: now - 30*day },\n"
"    { name: \"BlockBoy\", is_dir: true, size: 0, mtime: now - 2*day },\n"
"    { name: \"music\", is_dir: true, size: 0, mtime: now - 12*day },\n"
"    { name: \"crash.log\", is_dir: false, size: 2467, mtime: now - 5*day },\n"
"  ],\n"
"  \"/sd/roms\": [\n"
"    { name: \"gb\", is_dir: true, size: 0, mtime: now - 30*day },\n"
"    { name: \"gbc\", is_dir: true, size: 0, mtime: now - 30*day },\n"
"    { name: \"nes\", is_dir: true, size: 0, mtime: now - 30*day },\n"
"    { name: \"gba\", is_dir: true, size: 0, mtime: now - 8*day },\n"
"  ],\n"
"  \"/sd/roms/gb\": [\n"
"    { name: \"Tobu Tobu Girl.gb\", is_dir: false, size: 262144, mtime: now - 9*day },\n"
"    { name: \"Deadeus.gb\", is_dir: false, size: 524288, mtime: now - 21*day },\n"
"    { name: \"uCity.gb\", is_dir: false, size: 1048576, mtime: now - 3*day },\n"
"  ],\n"
"  \"/sd/roms/gbc\": [{ name: \"Petris.gbc\", is_dir: false, size: 1048576, mtime: now - 15*day }],\n"
"  \"/sd/roms/nes\": [], \"/sd/roms/gba\": [], \"/sd/music\": [],\n"
"  \"/sd/romart\": [{ name: \"gb\", is_dir: true, size: 0, mtime: now - 30*day }],\n"
"  \"/sd/romart/gb\": [{ name: \"Tobu Tobu Girl.png\", is_dir: false, size: 18740, mtime: now - 9*day }],\n"
"  \"/sd/BlockBoy\": [\n"
"    { name: \"config\", is_dir: true, size: 0, mtime: now - day },\n"
"    { name: \"saves\", is_dir: true, size: 0, mtime: now - day },\n"
"  ],\n"
"  \"/sd/BlockBoy/config\": [{ name: \"global.json\", is_dir: false, size: 1210, mtime: now - day }],\n"
"  \"/sd/BlockBoy/saves\": [\n"
"    { name: \"gb\", is_dir: true, size: 0, mtime: now - day },\n"
"  ],\n"
"  \"/sd/BlockBoy/saves/gb\": [\n"
"    { name: \"Tobu Tobu Girl.gb.sav\", is_dir: false, size: 32768, mtime: now - day },\n"
"    { name: \"Deadeus.gb.state\", is_dir: false, size: 189214, mtime: now - 2*day },\n"
"  ],\n"
"};\n"
"function demoApi(cmd, a1, a2) {\n"
"  const dir = p => demoFS[p] || (demoFS[p] = []);\n"
"  const split = p => [p.slice(0, p.lastIndexOf(\"/\")), p.slice(p.lastIndexOf(\"/\") + 1)];\n"
"  if (cmd === \"list\") return { success: true, files: dir(a1).slice() };\n"
"  if (cmd === \"stat\") return {\n"
"    success: true, battery: 87, charging: false,\n"
"    version: \"V3-N16R8-2.0\", free: 24816000000, total: 31914983424,\n"
"  };\n"
"  if (cmd === \"play\") return { success: true };\n"
"  if (cmd === \"mkdir\") {\n"
"    const [d, n] = split(a1);\n"
"    dir(d).push({ name: n, is_dir: true, size: 0, mtime: now });\n"
"    demoFS[a1] = [];\n"
"    return { success: true };\n"
"  }\n"
"  if (cmd === \"delete\") {\n"
"    const [d, n] = split(a1);\n"
"    demoFS[d] = dir(d).filter(f => f.name !== n);\n"
"    return { success: true };\n"
"  }\n"
"  if (cmd === \"rename\") {\n"
"    const [d, n] = split(a1), [d2, n2] = split(a2);\n"
"    const f = dir(d).find(f => f.name === n);\n"
"    if (f) { demoFS[d] = dir(d).filter(x => x.name !== n); dir(d2).push({ ...f, name: n2 }); }\n"
"    return { success: true };\n"
"  }\n"
"  return { success: false };\n"
"}\n"
"\n"
"/* ---------- API ---------- */\n"
"async function api(cmd, arg1, arg2) {\n"
"  if (demo) return demoApi(cmd, arg1, arg2);\n"
"  try {\n"
"    const r = await fetch(\"/api\", {\n"
"      method: \"POST\",\n"
"      body: JSON.stringify({ cmd, arg1: arg1 || \"\", arg2: arg2 || \"\" }),\n"
"    });\n"
"    return await r.json();\n"
"  } catch (e) {\n"
"    if (cmd === \"list\" && !demo) {\n"
"      demo = true;\n"
"      document.body.classList.add(\"demo\");\n"
"      toast(\"No BlockBoy found — showing demo files\");\n"
"      loadStat();\n"
"      return demoApi(cmd, arg1, arg2);\n"
"    }\n"
"    return { success: false };\n"
"  }\n"
"}\n"
"\n"
"/* ---------- device status ---------- */\n"
"async function loadStat() {\n"
"  const s = await api(\"stat\");\n"
"  if (!s || !s.success) return; // older firmware: keep the strip hidden\n"
"  const bar = $(\"#devbar\");\n"
"  bar.classList.add(\"on\");\n"
"  const lvl = Math.max(0, Math.min(100, Math.round(s.battery)));\n"
"  $(\"#batt\").style.setProperty(\"--lvl\", lvl + \"%\");\n"
"  $(\"#batt\").classList.toggle(\"low\", lvl <= 20 && !s.charging);\n"
"  $(\"#batt-txt\").textContent = lvl + \"%\" + (s.charging ? \" ⚡\" : \"\");\n"
"  $(\"#fw-txt\").textContent = s.version || \"\";\n"
"  if (s.total > 0) {\n"
"    const used = s.total - s.free;\n"
"    $(\"#space-txt\").textContent = fmtSize(s.free) + \" free\";\n"
"    $(\"#space-fill\").style.setProperty(\"--used\", Math.round(used / s.total * 100) + \"%\");\n"
"  }\n"
"}\n"
"\n"
"/* ---------- state: sort / search / selection ---------- */\n"
"const SORTS = [\n"
"  [\"name\",  \"Name A–Z\"],\n"
"  [\"-name\", \"Name Z–A\"],\n"
"  [\"-mtime\",\"Newest first\"],\n"
"  [\"mtime\", \"Oldest first\"],\n"
"  [\"-size\", \"Largest first\"],\n"
"  [\"size\",  \"Smallest first\"],\n"
"];\n"
"let sortMode = \"name\";\n"
"let query = \"\";\n"
"let selMode = false;\n"
"let selected = new Set();\n"
"\n"
"function applySort(arr) {\n"
"  const key = sortMode.replace(\"-\", \"\");\n"
"  const dir = sortMode.startsWith(\"-\") ? -1 : 1;\n"
"  arr.sort((a, b) => {\n"
"    if (key === \"name\") return dir * a.name.localeCompare(b.name, undefined, { sensitivity: \"base\", numeric: true });\n"
"    return dir * ((a[key] || 0) - (b[key] || 0)) || a.name.localeCompare(b.name);\n"
"  });\n"
"  arr.sort((a, b) => b.is_dir - a.is_dir);\n"
"  return arr;\n"
"}\n"
"\n"
"/* ---------- rendering ---------- */\n"
"function renderPath() {\n"
"  const parts = path.slice(1).split(\"/\");\n"
"  let acc = \"\", html = \"\";\n"
"  parts.forEach((p, i) => {\n"
"    acc += \"/\" + p;\n"
"    const label = i === 0 ? \"SD\" : p;\n"
"    if (i === parts.length - 1) html += `<span class=\"here\">${esc(label)}</span>`;\n"
"    else html += `<button data-nav=\"${esc(acc)}\">${esc(label)}</button><span class=\"sep\">/</span>`;\n"
"  });\n"
"  $(\"#pathbar\").innerHTML = html;\n"
"}\n"
"\n"
"let files = [];\n"
"function visibleFiles() {\n"
"  const q = query.trim().toLowerCase();\n"
"  return q ? files.filter(f => f.name.toLowerCase().includes(q)) : files.slice();\n"
"}\n"
"\n"
"function render() {\n"
"  const shown = applySort(visibleFiles());\n"
"  let html = \"\";\n"
"  if (path !== ROOT && !selMode && !query) {\n"
"    html += `<div class=\"row\" role=\"listitem\" tabindex=\"0\" data-up=\"1\">\n"
"      <span class=\"fic\"><svg width=\"20\" height=\"20\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"var(--muted)\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 13V4M4 7.5L8 3.5l4 4\"/><path d=\"M2 14.5h12\" opacity=\"0.4\"/></svg></span>\n"
"      <span class=\"info\">\n"
"        <span class=\"name\" style=\"color:var(--muted)\">..</span>\n"
"        <span class=\"meta\">back to ${esc(parentOf(path) === ROOT ? \"SD\" : parentOf(path).split(\"/\").pop())}</span>\n"
"      </span>\n"
"    </div>`;\n"
"  }\n"
"  shown.forEach(f => {\n"
"    const checked = selected.has(f.name);\n"
"    html += `<div class=\"row${checked ? \" checked\" : \"\"}\" role=\"listitem\" tabindex=\"0\" data-name=\"${esc(f.name)}\">\n"
"      <span class=\"fic\">${selMode ? `<span class=\"cbox\"><svg width=\"12\" height=\"12\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"3\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.5 8.5l3.5 3.5 7-8\"/></svg></span>` : icon(f)}</span>\n"
"      <span class=\"info\">\n"
"        <span class=\"name\">${esc(f.name)}${f.is_dir ? \"/\" : \"\"}</span>\n"
"        <span class=\"meta\">${f.is_dir ? \"\" : fmtSize(f.size) + \" · \"}${fmtDate(f.mtime)}</span>\n"
"      </span>\n"
"      ${selMode ? \"\" : `<button class=\"kebab\" data-menu=\"${esc(f.name)}\" aria-label=\"Actions for ${esc(f.name)}\">\n"
"        <svg width=\"18\" height=\"18\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><circle cx=\"8\" cy=\"3.5\" r=\"1.5\"/><circle cx=\"8\" cy=\"8\" r=\"1.5\"/><circle cx=\"8\" cy=\"12.5\" r=\"1.5\"/></svg>\n"
"      </button>`}\n"
"    </div>`;\n"
"  });\n"
"  if (!shown.length) {\n"
"    html += query\n"
"      ? `<div class=\"empty\"><b>No matches</b>Nothing in this folder matches \"${esc(query)}\".</div>`\n"
"      : `<div class=\"empty\"><b>Empty folder</b>Upload files or create a folder here.</div>`;\n"
"  }\n"
"  $(\"#list\").innerHTML = html;\n"
"  const nd = shown.filter(f => f.is_dir).length;\n"
"  $(\"#count\").textContent = shown.length\n"
"    ? `${nd} folder${nd === 1 ? \"\" : \"s\"} · ${shown.length - nd} file${shown.length - nd === 1 ? \"\" : \"s\"}`\n"
"    : \"\";\n"
"  $(\"#bulk-n\").textContent = selected.size + \" selected\";\n"
"  $(\"#bulkbar\").classList.toggle(\"on\", selMode);\n"
"}\n"
"\n"
"async function load(p, fromHistory) {\n"
"  const res = await api(\"list\", p);\n"
"  if (!res.success) { toast(\"Could not open folder\"); return; }\n"
"  if (!fromHistory && p !== path) history.pushState({ p }, \"\");\n"
"  path = p;\n"
"  files = res.files || [];\n"
"  query = \"\";\n"
"  $(\"#search\").value = \"\";\n"
"  $(\"#searchrow\").classList.remove(\"has-q\");\n"
"  exitSelect(false);\n"
"  renderPath();\n"
"  render();\n"
"}\n"
"\n"
"/* ---------- actions ---------- */\n"
"function download(f) {\n"
"  if (demo) { toast(\"Download is not available in the demo\"); return; }\n"
"  const a = document.createElement(\"a\");\n"
"  a.href = urlPath(path + \"/\" + f.name);\n"
"  a.download = f.name;\n"
"  a.click();\n"
"}\n"
"\n"
"function modal({ title, text, value, okLabel, danger, onok }) {\n"
"  $(\"#m-title\").textContent = title;\n"
"  $(\"#m-text\").textContent = text || \"\";\n"
"  const inp = $(\"#m-input\");\n"
"  inp.style.display = value === undefined ? \"none\" : \"\";\n"
"  inp.value = value || \"\";\n"
"  const ok = $(\"#m-ok\");\n"
"  ok.textContent = okLabel || \"OK\";\n"
"  ok.classList.toggle(\"danger\", !!danger);\n"
"  ok.classList.toggle(\"primary\", !danger);\n"
"  $(\"#modal\").classList.add(\"open\");\n"
"  if (value !== undefined) {\n"
"    inp.focus();\n"
"    const dot = inp.value.lastIndexOf(\".\");\n"
"    inp.setSelectionRange(0, dot > 0 ? dot : inp.value.length);\n"
"  } else ok.focus();\n"
"  const close = () => { $(\"#modal\").classList.remove(\"open\"); ok.onclick = null; inp.onkeydown = null; };\n"
"  $(\"#m-cancel\").onclick = close;\n"
"  ok.onclick = () => { const v = inp.value.trim(); close(); onok(v); };\n"
"  inp.onkeydown = e => { if (e.key === \"Enter\") ok.onclick(); if (e.key === \"Escape\") close(); };\n"
"}\n"
"\n"
"/* ---------- viewer (images & text) ---------- */\n"
"async function view(f) {\n"
"  const full = path + \"/\" + f.name;\n"
"  $(\"#v-title\").textContent = f.name;\n"
"  const img = $(\"#v-img\"), pre = $(\"#v-pre\");\n"
"  img.hidden = true; pre.hidden = true;\n"
"  if (isImg(f)) {\n"
"    if (demo) { toast(\"Preview is not available in the demo\"); return; }\n"
"    img.onerror = () => { $(\"#viewer\").classList.remove(\"open\"); toast(\"Could not open image\"); };\n"
"    img.src = urlPath(full); img.hidden = false;\n"
"  } else {\n"
"    if (demo) {\n"
"      pre.textContent = \"[demo] \" + f.name + \"\\n\\nOn the real BlockBoy the file contents\\nare shown here.\";\n"
"      pre.hidden = false;\n"
"    } else {\n"
"      try {\n"
"        const r = await fetch(urlPath(full));\n"
"        let t = await r.text();\n"
"        if (t.length > 60000) t = t.slice(0, 60000) + \"\\n… (truncated)\";\n"
"        pre.textContent = t; pre.hidden = false;\n"
"      } catch (e) { toast(\"Could not open file\"); return; }\n"
"    }\n"
"  }\n"
"  $(\"#viewer\").classList.add(\"open\");\n"
"  $(\"#v-download\").onclick = () => download(f);\n"
"  $(\"#v-close\").onclick = () => {\n"
"    $(\"#viewer\").classList.remove(\"open\");\n"
"    img.removeAttribute(\"src\");\n"
"  };\n"
"}\n"
"\n"
"/* ---------- folder picker (move) ---------- */\n"
"function pickFolder(title, cb) {\n"
"  let pp = path;\n"
"  const render = async () => {\n"
"    $(\"#p-path\").textContent = pp;\n"
"    const res = await api(\"list\", pp);\n"
"    const dirs = (res.files || []).filter(f => f.is_dir)\n"
"      .sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: \"base\" }));\n"
"    let html = \"\";\n"
"    if (pp !== ROOT)\n"
"      html += `<button data-go=\"${esc(parentOf(pp))}\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"var(--muted)\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 13V4M4 7.5L8 3.5l4 4\"/></svg> ..</button>`;\n"
"    for (const d of dirs)\n"
"      html += `<button data-go=\"${esc(pp + \"/\" + d.name)}\"><svg width=\"16\" height=\"16\" viewBox=\"0 0 16 16\" fill=\"var(--accent)\"><path d=\"M1.5 4a1 1 0 0 1 1-1h3.6l1.4 1.5h6a1 1 0 0 1 1 1V12a1 1 0 0 1-1 1h-11a1 1 0 0 1-1-1z\"/></svg> ${esc(d.name)}</button>`;\n"
"    if (!html) html = `<div class=\"none\">No subfolders</div>`;\n"
"    $(\"#p-list\").innerHTML = html;\n"
"  };\n"
"  $(\"#p-list\").onclick = e => {\n"
"    const b = e.target.closest(\"[data-go]\");\n"
"    if (b) { pp = b.dataset.go; render(); }\n"
"  };\n"
"  $(\"#p-cancel\").onclick = () => $(\"#picker\").classList.remove(\"open\");\n"
"  $(\"#p-ok\").onclick = () => { $(\"#picker\").classList.remove(\"open\"); cb(pp); };\n"
"  $(\"#picker\").classList.add(\"open\");\n"
"  render();\n"
"}\n"
"\n"
"async function moveFiles(names, dest) {\n"
"  if (dest === path) { toast(\"Already in this folder\"); return; }\n"
"  let ok = 0;\n"
"  for (const n of names) {\n"
"    const r = await api(\"rename\", path + \"/\" + n, dest + \"/\" + n);\n"
"    if (r.success) ok++;\n"
"  }\n"
"  toast(ok === names.length ? `Moved ${ok} item${ok === 1 ? \"\" : \"s\"}` : `Moved ${ok}/${names.length} — some failed`);\n"
"  load(path);\n"
"}\n"
"\n"
"/* ---------- selection mode ---------- */\n"
"function enterSelect() { selMode = true; selected.clear(); $(\"#btn-select\").classList.add(\"active\"); render(); }\n"
"function exitSelect(rerender = true) {\n"
"  selMode = false; selected.clear();\n"
"  $(\"#btn-select\").classList.remove(\"active\");\n"
"  if (rerender) render();\n"
"  else $(\"#bulkbar\").classList.remove(\"on\");\n"
"}\n"
"\n"
"/* ---------- item menu ---------- */\n"
"function openMenu(name, anchor) {\n"
"  const f = files.find(x => x.name === name);\n"
"  if (!f) return;\n"
"  const full = path + \"/\" + f.name;\n"
"  const it = (id, label, svg, danger) =>\n"
"    `<button class=\"item${danger ? \" danger\" : \"\"}\" data-act=\"${id}\">${svg}${label}</button>`;\n"
"  const sheet = $(\"#sheet\");\n"
"  let items = \"\";\n"
"  if (f.is_dir) items += it(\"open\", \"Open\", `<svg width=\"17\" height=\"17\" viewBox=\"0 0 16 16\" fill=\"var(--accent)\"><path d=\"M1.5 4a1 1 0 0 1 1-1h3.6l1.4 1.5h6a1 1 0 0 1 1 1V12a1 1 0 0 1-1 1h-11a1 1 0 0 1-1-1z\"/></svg>`);\n"
"  if (isRom(f)) items += it(\"play\", \"Play on BlockBoy\", `<svg width=\"17\" height=\"17\" viewBox=\"0 0 16 16\" fill=\"currentColor\"><path d=\"M4 2.5v11l9-5.5z\"/></svg>`);\n"
"  if (isImg(f) || isTxt(f)) items += it(\"view\", \"View\", `<svg width=\"17\" height=\"17\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\"><path d=\"M1.5 8s2.5-4.5 6.5-4.5S14.5 8 14.5 8 12 12.5 8 12.5 1.5 8 1.5 8z\"/><circle cx=\"8\" cy=\"8\" r=\"2\"/></svg>`);\n"
"  if (!f.is_dir) items += it(\"download\", \"Download\", `<svg width=\"17\" height=\"17\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 3v8M4 8l4 4 4-4M2 14h12\"/></svg>`);\n"
"  items += it(\"move\", \"Move to…\", `<svg width=\"17\" height=\"17\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M1.5 4.5v8h13v-6.5H8L6.5 4.5z\"/><path d=\"M8 8.5h4M10.5 7L12 8.5 10.5 10\"/></svg>`);\n"
"  items += it(\"rename\", \"Rename\", `<svg width=\"17\" height=\"17\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9.5 3.5l3 3L5 14H2v-3z\"/><path d=\"M11.5 1.5l3 3\"/></svg>`);\n"
"  items += it(\"delete\", \"Delete\", `<svg width=\"17\" height=\"17\" viewBox=\"0 0 16 16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.6\" stroke-linecap=\"round\"><path d=\"M2.5 4h11M6.5 2h3M4 4l.8 10h6.4L12 4M6.5 7v4.5M9.5 7v4.5\"/></svg>`, true);\n"
"  sheet.innerHTML = `<div class=\"grip\"></div><h4>${esc(f.name)}</h4>` + items;\n"
"  showSheet();\n"
"  if (matchMedia(\"(min-width: 640px)\").matches && anchor) {\n"
"    const r = anchor.getBoundingClientRect();\n"
"    sheet.style.top = (r.bottom + scrollY + 4) + \"px\";\n"
"    sheet.style.left = Math.max(8, Math.min(r.right + scrollX - 230, innerWidth - 242)) + \"px\";\n"
"  } else {\n"
"    sheet.style.top = \"\"; sheet.style.left = \"\";\n"
"  }\n"
"  sheet.onclick = async e => {\n"
"    const act = e.target.closest(\"[data-act]\")?.dataset.act;\n"
"    if (!act) return;\n"
"    closeMenu();\n"
"    if (act === \"open\") load(full);\n"
"    if (act === \"download\") download(f);\n"
"    if (act === \"view\") view(f);\n"
"    if (act === \"move\") pickFolder(\"Move\", dest => moveFiles([f.name], dest));\n"
"    if (act === \"play\") {\n"
"      const r = await api(\"play\", full);\n"
"      toast(r.success ? (demo ? \"▶ (demo) BlockBoy would now start \" + f.name : \"▶ Starting on BlockBoy…\")\n"
"                      : \"Could not start the game\");\n"
"    }\n"
"    if (act === \"rename\") modal({\n"
"      title: \"Rename\", value: f.name, okLabel: \"Rename\",\n"
"      onok: async v => {\n"
"        if (!v || v === f.name) return;\n"
"        const r = await api(\"rename\", full, path + \"/\" + v);\n"
"        toast(r.success ? \"Renamed\" : \"Rename failed\");\n"
"        load(path);\n"
"      },\n"
"    });\n"
"    if (act === \"delete\") modal({\n"
"      title: f.is_dir ? \"Delete folder?\" : \"Delete file?\",\n"
"      text: f.name + (f.is_dir ? \" — the folder must be empty.\" : \" will be removed from the SD card.\"),\n"
"      okLabel: \"Delete\", danger: true,\n"
"      onok: async () => {\n"
"        const r = await api(\"delete\", full);\n"
"        toast(r.success ? \"Deleted\" : \"Delete failed (folder not empty?)\");\n"
"        load(path);\n"
"      },\n"
"    });\n"
"  };\n"
"}\n"
"// Any pointerdown that isn't inside the sheet closes it. Registered one tick\n"
"// after opening so the very click that opened the menu doesn't close it again.\n"
"function onOutsidePointer(e) {\n"
"  if (!e.target.closest(\"#sheet\")) closeMenu();\n"
"}\n"
"function showSheet() {\n"
"  $(\"#scrim\").classList.add(\"open\");\n"
"  $(\"#sheet\").classList.add(\"open\");\n"
"  setTimeout(() => document.addEventListener(\"pointerdown\", onOutsidePointer), 0);\n"
"}\n"
"function closeMenu() {\n"
"  document.removeEventListener(\"pointerdown\", onOutsidePointer);\n"
"  $(\"#sheet\").classList.remove(\"open\");\n"
"  $(\"#scrim\").classList.remove(\"open\");\n"
"}\n"
"\n"
"/* ---------- sort menu ---------- */\n"
"function openSortMenu(anchor) {\n"
"  const sheet = $(\"#sheet\");\n"
"  sheet.innerHTML = `<div class=\"grip\"></div><h4>Sort by</h4>` + SORTS.map(([id, label]) =>\n"
"    `<button class=\"item\" data-sort=\"${id}\">${label}${sortMode === id ? `<span class=\"now\">✓</span>` : \"\"}</button>`\n"
"  ).join(\"\");\n"
"  showSheet();\n"
"  if (matchMedia(\"(min-width: 640px)\").matches && anchor) {\n"
"    const r = anchor.getBoundingClientRect();\n"
"    sheet.style.top = (r.bottom + scrollY + 4) + \"px\";\n"
"    sheet.style.left = Math.max(8, Math.min(r.right + scrollX - 230, innerWidth - 242)) + \"px\";\n"
"  } else { sheet.style.top = \"\"; sheet.style.left = \"\"; }\n"
"  sheet.onclick = e => {\n"
"    const s = e.target.closest(\"[data-sort]\")?.dataset.sort;\n"
"    if (!s) return;\n"
"    sortMode = s;\n"
"    closeMenu();\n"
"    render();\n"
"  };\n"
"}\n"
"\n"
"/* ---------- uploads ---------- */\n"
"function uploadFiles(fileList) {\n"
"  for (const file of fileList) {\n"
"    const el = document.createElement(\"div\");\n"
"    el.className = \"up-item\";\n"
"    el.innerHTML = `<div class=\"nm\"><span>${esc(file.name)}</span><em>0%</em></div>\n"
"                    <div class=\"track\"><div class=\"fill\"></div></div>`;\n"
"    $(\"#uploads\").appendChild(el);\n"
"    const done = ok => {\n"
"      el.querySelector(\"em\").textContent = ok ? \"done\" : \"failed\";\n"
"      el.querySelector(\".fill\").style.background = ok ? \"var(--accent)\" : \"var(--danger)\";\n"
"      setTimeout(() => { el.remove(); load(path); }, ok ? 900 : 3200);\n"
"    };\n"
"    if (demo) {\n"
"      let p = 0;\n"
"      const iv = setInterval(() => {\n"
"        p = Math.min(100, p + 8 + Math.random() * 14);\n"
"        el.querySelector(\".fill\").style.width = p + \"%\";\n"
"        el.querySelector(\"em\").textContent = Math.floor(p) + \"%\";\n"
"        if (p >= 100) {\n"
"          clearInterval(iv);\n"
"          (demoFS[path] = demoFS[path] || []).push({ name: file.name, is_dir: false, size: file.size, mtime: now });\n"
"          done(true);\n"
"        }\n"
"      }, 120);\n"
"      continue;\n"
"    }\n"
"    const xhr = new XMLHttpRequest();\n"
"    xhr.upload.addEventListener(\"progress\", e => {\n"
"      const pct = Math.floor(e.loaded / e.total * 100);\n"
"      el.querySelector(\".fill\").style.width = pct + \"%\";\n"
"      el.querySelector(\"em\").textContent = pct + \"%\";\n"
"    });\n"
"    xhr.addEventListener(\"load\", () => done(xhr.status < 400 && xhr.responseText.indexOf(\"ERROR\") < 0));\n"
"    xhr.addEventListener(\"error\", () => done(false));\n"
"    xhr.open(\"PUT\", urlPath(path + \"/\" + file.name));\n"
"    xhr.send(file);\n"
"  }\n"
"}\n"
"\n"
"/* ---------- wiring ---------- */\n"
"$(\"#btn-upload\").onclick = () => $(\"#upload\").click();\n"
"$(\"#upload\").onchange = e => { uploadFiles(e.target.files); e.target.value = \"\"; };\n"
"$(\"#btn-refresh\").onclick = () => { load(path); loadStat(); toast(\"Refreshed\"); };\n"
"$(\"#btn-sort\").onclick = e => openSortMenu(e.currentTarget);\n"
"$(\"#btn-select\").onclick = () => selMode ? exitSelect() : enterSelect();\n"
"$(\"#btn-newfolder\").onclick = () => modal({\n"
"  title: \"New folder\", value: \"\", okLabel: \"Create\",\n"
"  onok: async v => {\n"
"    if (!v) return;\n"
"    const r = await api(\"mkdir\", path + \"/\" + v);\n"
"    toast(r.success ? \"Folder created\" : \"Could not create folder\");\n"
"    load(path);\n"
"  },\n"
"});\n"
"$(\"#search\").oninput = e => {\n"
"  query = e.target.value;\n"
"  $(\"#searchrow\").classList.toggle(\"has-q\", !!query);\n"
"  render();\n"
"};\n"
"$(\"#search-clear\").onclick = () => {\n"
"  query = \"\"; $(\"#search\").value = \"\";\n"
"  $(\"#searchrow\").classList.remove(\"has-q\");\n"
"  render(); $(\"#search\").focus();\n"
"};\n"
"$(\"#pathbar\").onclick = e => {\n"
"  const nav = e.target.closest(\"[data-nav]\");\n"
"  if (nav) load(nav.dataset.nav);\n"
"};\n"
"\n"
"function activateRow(row) {\n"
"  if (row.dataset.up) { load(parentOf(path)); return; }\n"
"  const f = files.find(x => x.name === row.dataset.name);\n"
"  if (!f) return;\n"
"  if (selMode) {\n"
"    if (selected.has(f.name)) selected.delete(f.name);\n"
"    else selected.add(f.name);\n"
"    render();\n"
"    return;\n"
"  }\n"
"  // Tapping never downloads: folders open, images/text preview, everything\n"
"  // else opens the action menu (Play / Download / …). This avoids the phone\n"
"  // firing an unwanted download the moment you tap a ROM.\n"
"  if (f.is_dir) load(path + \"/\" + f.name);\n"
"  else if (isImg(f) || isTxt(f)) view(f);\n"
"  else openMenu(f.name, row.querySelector(\".kebab\"));\n"
"}\n"
"$(\"#list\").onclick = e => {\n"
"  const kb = e.target.closest(\"[data-menu]\");\n"
"  if (kb) { openMenu(kb.dataset.menu, kb); return; }\n"
"  const row = e.target.closest(\".row\");\n"
"  if (row) activateRow(row);\n"
"};\n"
"$(\"#list\").onkeydown = e => {\n"
"  if (e.key !== \"Enter\" && e.key !== \" \") return;\n"
"  const row = e.target.closest(\".row\");\n"
"  if (!row) return;\n"
"  e.preventDefault();\n"
"  activateRow(row);\n"
"};\n"
"\n"
"/* bulk actions */\n"
"$(\"#bulk-cancel\").onclick = () => exitSelect();\n"
"$(\"#bulk-download\").onclick = () => {\n"
"  const items = files.filter(f => selected.has(f.name) && !f.is_dir);\n"
"  if (!items.length) { toast(\"No files selected (folders can't be downloaded)\"); return; }\n"
"  if (demo) { toast(\"Download is not available in the demo\"); return; }\n"
"  let i = 0;\n"
"  const next = () => {\n"
"    if (i >= items.length) return;\n"
"    download(items[i++]);\n"
"    setTimeout(next, 600);\n"
"  };\n"
"  next();\n"
"  toast(`Downloading ${items.length} file${items.length === 1 ? \"\" : \"s\"}…`);\n"
"};\n"
"$(\"#bulk-move\").onclick = () => {\n"
"  if (!selected.size) { toast(\"Nothing selected\"); return; }\n"
"  pickFolder(\"Move\", dest => moveFiles([...selected], dest));\n"
"};\n"
"$(\"#bulk-delete\").onclick = () => {\n"
"  if (!selected.size) { toast(\"Nothing selected\"); return; }\n"
"  const names = [...selected];\n"
"  modal({\n"
"    title: `Delete ${names.length} item${names.length === 1 ? \"\" : \"s\"}?`,\n"
"    text: \"They will be removed from the SD card. Folders must be empty.\",\n"
"    okLabel: \"Delete\", danger: true,\n"
"    onok: async () => {\n"
"      let ok = 0;\n"
"      for (const n of names) {\n"
"        const r = await api(\"delete\", path + \"/\" + n);\n"
"        if (r.success) ok++;\n"
"      }\n"
"      toast(ok === names.length ? \"Deleted\" : `Deleted ${ok}/${names.length} — some failed`);\n"
"      load(path);\n"
"    },\n"
"  });\n"
"};\n"
"\n"
"// pointerdown (not click) so a tap on the backdrop dismisses reliably on touch.\n"
"$(\"#scrim\").addEventListener(\"pointerdown\", closeMenu);\n"
"$(\"#scrim\").addEventListener(\"click\", closeMenu);\n"
"addEventListener(\"keydown\", e => {\n"
"  if (e.key === \"Escape\") {\n"
"    closeMenu();\n"
"    $(\"#modal\").classList.remove(\"open\");\n"
"    $(\"#picker\").classList.remove(\"open\");\n"
"    $(\"#viewer\").classList.remove(\"open\");\n"
"  }\n"
"});\n"
"\n"
"/* phone/browser back button walks back through visited folders */\n"
"history.replaceState({ p: ROOT }, \"\");\n"
"addEventListener(\"popstate\", e => {\n"
"  closeMenu();\n"
"  $(\"#modal\").classList.remove(\"open\");\n"
"  $(\"#picker\").classList.remove(\"open\");\n"
"  $(\"#viewer\").classList.remove(\"open\");\n"
"  load((e.state && e.state.p) || ROOT, true);\n"
"});\n"
"\n"
"/* drag & drop (desktop) */\n"
"let dragDepth = 0;\n"
"addEventListener(\"dragenter\", e => { e.preventDefault(); if (++dragDepth) document.body.classList.add(\"dragging\"); });\n"
"addEventListener(\"dragleave\", () => { if (--dragDepth <= 0) { dragDepth = 0; document.body.classList.remove(\"dragging\"); } });\n"
"addEventListener(\"dragover\", e => e.preventDefault());\n"
"addEventListener(\"drop\", e => {\n"
"  e.preventDefault();\n"
"  dragDepth = 0;\n"
"  document.body.classList.remove(\"dragging\");\n"
"  if (e.dataTransfer.files.length) uploadFiles(e.dataTransfer.files);\n"
"});\n"
"\n"
"load(ROOT);\n"
"loadStat();\n"
"</script>\n"
"</body></html>\n"
;
